#
# SPDX-License-Identifier: Apache-2.0
#

version: "2.1"

networks:
  carbonAccounting:

services:
  chaincode-utilityemissions2:
    container_name: chaincode-utilityemissions2.carbonAccounting.com
    image: krybalko/utilityemissions-chaincode:0.0.3
    environment:
      - CHAINCODE_CCID=utilityemissions:c56c9b4072b2d28394b7e63d73d4d969b20cd248ccf2138ea84a445035852c54
      - CHAINCODE_ADDRESS=0.0.0.0:9999
    ports:
      - "9999:9999"
