// export { tokenDefinitionData };
exports.tokenId = 1;
exports.allTokenTypeId = ["Renewable Energy Certificate", "Carbon Emissions Offset", "Audited Emissions"];
exports.quantity = 10;
exports.issuerId = "issuer";
exports.recipientId = "recipient";
exports.uom = "uom";
exports.fromDate = "1/1/20";
exports.thruDate = "12/31/20";
exports.metadata = "metaData";
exports.manifest = "manifest";
exports.description = "description";
exports.automaticRetireDate = "12/31/21";
