// export { tokenDefinitionData };
exports.tokenId = 1;
exports.allTokenTypeId = ["Renewable Energy Certificate", "Carbon Emissions Offset", "Audited Emissions"];
exports.quantity = 10;
exports.issuerId = "issuer";
exports.recipientId = "recipient";
exports.uom = "uom";
exports.fromDate = "1607463809";
exports.thruDate = "1607463909";
exports.metadata = "metaData";
exports.manifest = "manifest";
exports.description = "description";
exports.automaticRetireDate = "1607464809";
