package model

// model.output.go : input type definition of output from request manager chaincode

type StageUpdateOutput struct {
	// FabricDataLock : output generate by each data chaincode after executing data chaincode
	// before locking data
	// key of the map : chaincodeName
	// value of the map : output generated by data chaincode
	FabricDataLocks map[string]string `json:"fabricDataLocks"`

	// FabricDataFree : output generate by each data chaincode after executing data chaincode
	// before freeing data
	// key of the map : chaincodeName
	// value of the map : output generated by data chaincode
	FabricDataFree map[string]string `json:"fabricDataFree"`
}

type FabricDataLocks struct {
	Chaincode string `json:"chaincode"`
	Key       string `json:"key"`
}
