export const CATF_COMPANY_NAME_SEARCH: { [key: string]: string[] } = {
  "Abraxas Petroleum": ["Abraxas"],
  "Advance Energy Partners": [
     "ADVANCE DRLG"
    ,"ADVANCE EXPLORATION"
    ,"ADVANCE HYDROCARBON CORPORATION"
    ,"ADVANCE INDUSTRIES LLC"
    ,"ADVANCE OIL CORPORATION"
    ,"ADVANCE PETROLEUM RESOURCES"
    ,"ADVANCED PET"
  ],
  "Aethon Energy": ["Aethon"],
  "Antero Resources": ["Antero"],
  "Approach Resources": ["Approach"],
  "APR Operating": ["APR "],
  "ARD Operating": ["ARD "],
  "Armour Energy": [
    "Armour Pet",
    "Armour Prop",
    "Armour Res"
  ],
  "Arsenal Energy Holdings": ["ARSENAL ENERGY"],
  "Ascent Resources": ["Ascent"],
  "Atlas Energy Group": ["Atlas"],
  "Australis TMS": ["AUSTRAL OIL"],
  "Axia Energy II": ["Axia Energy"],
  "Ballard Petroleum Holdings": ["Ballard Petroleum","Ballard Exp","Ballard Oil"],
  "Battalion Oil": ["Battalion Oil"],
  "BCE-Mach": ["BCE-Mach"],
  "Bedrock Energy Partners": ["Bedrock Energy Partners"],
  "Birch Resources": ["BIRCH CORP", "BIRCH OIL", "Birch Op"],
  "Bison Oil & Gas Partners II": [
    "BISON DRLG",
    "BISON ENERGY",
    "BISON EXPLORATION DRILLING 1, LP",
    "BISON INC",
    "BISON OPERATING COMPANY, LLC",
    "BISON PETROLEUM",
    "BISON PRODUCTION CO.",
    "BISON RESOURCES, INC.",
    "BISON, INC.",
  ],
  "BHP Minerals": ["BHP "],
  "BKV Operating": [
     "BKV"
    ,"Barnett Dr"
    ,"BARNETT Oi"
    ,"Barnett Ene"
  ],
  "Blackbeard Operating": ["Blackbeard"],
  "Blackbrush O & G": ["Blackbrush"],
  "Bluecrest Energy": ["Bluecrest"],
  "Blue Ridge Mountain Resources": ["Blue Ridge", "Blueridge"],
  "Bluefin Resources": ["Bluefin"],
  "Bluestone Natural Resources": ["Bluestone"],
  "Bonanza Creek Energy": ["Bonanza"],
  "BP": [
    "BP AMER", 
    "BP E", 
    "BP EXP", 
    "BP OP",
    "BP P",
    "BP W"],
  "Breitburn Energy": ["Breitburn"],
  "Bridge Energy": ["BRIDGE"],
  "Bruin E&P Partners": ["Bruin"],
  "Burnett Oil": ["Burnett"],
  "Cabot Oil & Gas": ["Cabot"],
  "Caerus Oil & Gas": ["Caerus"],
  "Caelus Energy": ["Caelus"],
  "California Resources": ["CRC", "California Resources"],
  "Callon Petroleum": ["Callon P", "Callon O"],
  "Carrizo Oil & Gas": ["Carrizo"],
  "Cat Canyon Resources": ["Cat Canyon"],
  "Castleton Commodities International": ["CCI "],
  "Centennial Resource": ["Centennial"],
  "CCRP Operating": ['CCRP'],
  "Chaparral Energy": ["Chaparral", "Chaparreal"],
  "Chesapeake Energy": ['Chesapeake'],
  "Chevron": ['Chevron'],
  "Chief Oil & Gas": ["Chief"],
  "Chisholm Energy Holdings": ["Chisholm"],
  "Cimarex Energy": ["Cimarex"],
  "Citation Oil & Gas": ["Citation"],
  "Citizen Energy": ["Citizen"],
  "CNX Resources": ["CNX"],
  "Colt Alaska": ["Colt"],
  "Compass Production Partners": ["Compass"],
  "Comstock Resources": ["Comstock"],
  "Concho Resources": ["Concho"],
  "Confluence DJ": ["Confluence"],
  "Contango Resources": ["Contango"],
  "ConocoPhillips": ["Conoco"],
  "Consol Energy": ["Consol "],
  "Continental Resources": ["Continental",'CONTINTENTAL',"CONTINTNTAL"],
  "Contura Energy": ["Contura"],
  "Cook Inlet Energy": ["Cook Inlet"],
  "Covey Park Energy": ["Covey Park"],
  "Crestone Peak Resources": ["Crestone"],
  "Crescent Pass Energy": ["Crescent "],
  "Cross Timbers Energy": ["Cross Timbers"],
  "Crowheart Energy": ["Crowheart"],
  "Cub Creek Energy": ["Cub Creek"],
  "Daylight Petroleum": ["Daylight"],
  "Denbury Resources": ["Denbury"],
  "Devon Energy": ["Devon "],
  "Diamondback Energy": ["Diamondback"],
  "Discovery Natural Resources": [
    "Discovery N",
    "Discovery O",
    "Discovery P"],
  "Diversified Gas & Oil": [
    "Diversified e", 
    "Diversified p", 
    "Diversified r"
  ],
  "DJR Energy": ["DJR"],
  "Dominion Energy": ["Dominion"],
  "Dugan Production Corp": ["Dugan"],
  "Duncan Oil Properties": ["Duncan"],
  "Earthstone Energy": ["Earthstone E","Earthstone o"],
  "Eagle Petroleum": ["EAGLE PETROLEUM"],
  "Eagleridge Operating": ["EAGLERIDGE OPERATING"],
  "Eastland Oil": ["Eastland"],
  "Edgemarc Energy Holdings": ["Edgemarc Energy"],
  "Elk Petroleum": ["ELK "],
  "Encana Oil & Gas": ["Encana"],
  "Encino Energy": ["Encino"],
  "Endeavor Energy Resources": ["Endeavor", "Endeavour"],
  "Enduring Resources": ["Enduring"],
  "Energy Corporation of America": [
    "ENERGY CORP OF AMER", 
    "ENERGY CORP. OF AMERICA, INC.",
    "ENERGY CORPORATION OF AMERICA"
  ],
  "Enerplus Resources": ["Enerplus"],
  "EnerVest Operating": ["EnerVest"],
  "Ensign Natural Resources": ["ENSIGN OPERATING"],
  "EOG Resources": ["EOG"],
  "EP Energy": ["EP Energy"],
  "Equal Energy": ["Equal Energy"],
  "Equinor": ["Equinor"],
  "ExxonMobil": ["EXXON"],
  "Fasken Oil & Ranch": ["Fasken Oil"],
  "Foundation Energy": [
    "Foundation Ene",
    "Foundation Oil", 
    "Foundation Res"
  ],
  "G Arthur Donnelly III": ["DONNELLY, GEORGE A."],
  "GeoSouthern Energy": ["GeoSouthern"],
  "Glacier Oil & Gas": [
     "GLACIER ENERGY, INC."
    ,"GLACIER PARK COMPANY"
    ,"GLACIER PET"
    ,"GLACIER PRODUCTION, INC."
  ],
  "Gulfport Energy": ["Gulfport"],
  "GulfTex Energy III": ["GulfTex"],
  "Halcon Resources": ["Halcon"],
  "Hawkwood Energy Management": ["Hawkwood"],
  "Hess": ["Hess Corp","HESS OIL", "HESS PRODUCTION"],
  "Highpoint Resources": ["Highpoint"],
  "Hinkle Oil & Gas": ["Hinkle Oil"],
  "Hunt Consolidated": ["Hunt o","Hunt p", "Hunt e"],
  "Jagged Peak Energy": ["Jagged Peak Energy"],
  "Jan D O'Neill": ["O'Neill"],
  "Jay-Bee Oil & Gas": ["JAY-BEE OIL"],
  "JKLM Energy": ["JKM"],
  "JMA Energy": ["JMA"],
  "Jones Energy": [
    "Jones Energy",
    "JONES OIL",
    "JONES OPER",
    "JONES CO"
  ],
  "Jordan Development": [
    "JORDAN DEVELOPMENT",
    "JORDAN DRILLING",
    "JORDAN ENGINEERING",
    "JORDAN EXPLORATION"
  ],
  "Kaiser-Francis Oil": ["Kaiser"],
  "Kash Oil & Gas": ["Kash o"],
  "Kraken Oil & Gas": ["Kraken"],
  "Lambda Energy Resources": ["Lambda"],
  "Laredo Energy": ["Laredo Energy","Laredo Mid"],
  "Lewis Energy Group": ["Lewis Energy"],
  "Logos Resources": ["Logos"],
  "Lonestar Resources": ["Lonestar R","Lonestar O"],
  "Luxe Energy": ["LUXE OPERATING LLC"],
  "Macpherson Energy": ["Macpherson"],
  "Magnolia Oil & Gas": ["Magnolia"],
  "Marathon Oil": ["Marathon"],
  "Matador Resources": ["Matador"],
  "Maverick Natural Resources": ["Maverick"],
  "Memorial Resource Development": ["MEMORIAL EXP","MEMORIAL PRO"],
  "Merit Energy": ["Merit "],
  "Mesquite Energy": [" Mesquite"],
  "Mewbourne Oil": ["Mewbourne"],
  "Midstates Petroleum": ["Midstates"],
  "Mission Creek Opco": [
    "MISSION CORP",
    "MISSION o",
    "MISSION ENERGY",
    "MISSION PROD",
    "MISSION RES"
  ],
  "Missouri River Resources": ["Missouri River"],
  "Monadnock Resources": ["mon-dak","Monadnock"],
  "Montage Resources": ["Montage"],
  "Mountaineer Keystone": [
    "MOUNTAINEER KEYSTONE",
    "MOUNTAINEER OIL",
    "MOUNTAINEER STATE",
    "MOUNTAINEER TRADING", 
    "MOUNTAINEER WELL"
  ],
  "Murex Petroleum": ["Murex"],
  "Murphy": ["MURPHY EXP","MURPHY OIL","MURPHY PRODUCTION"],
  "Muskegon Development Co": ["Muskegon Development Co"],
  "Nadel & Gussman": ["Nadel"],
  "Naftex Operating": ["Naftex Operating"],
  "National Fuel Gas": ["National Fuel Gas"],
  "Natural Gas Partners": ["NATURAL G & O", 
    'NATURAL GAS & OIL', 'NATURAL GAS AND OIL',
    'NATURAL GAS COMPANY, INC., THE',
    'NATURAL GAS CORPORATION',
    'NATURAL GAS GATHERERS',
    'NATURAL GAS MKTG. & STORAGE CO.',
    'NATURAL GAS OPERATIONS CO.',
    'NATURAL GAS P/L CO OF AMER LLC'],
  "Newark E&P Operating": ["Newark"],
  "Newfield Exploration": ["Newfield"],
  "NextEra Energy": ["NextEra"],
  "Nine Point Energy Holdings": ["Nine Point"],
  "Noble Energy": ["Noble Energy"],
  "Northeast Natural Energy": ["Northeast Natural"],
  "Northern Colorado Oil & Gas": [
    "COLORADO CRUDE",
    "COLORADO O",
    "COLORADO PETROLEUM",
    "COLORADO GAS"
  ],
  "Northwoods Energy": ["Northwood"],
  "NP Resources": ["NP ENERGY CORPORATION"],
  "Oak Ridge Natural Resources": ["Oak Ridge"],
  "Oasis Petroleum": ["Oasis"],
  "Occidental": ["Occidental", "OXY L", "OXY P", "OXY U"],
  "Orx Resources": ["Orx Resources"],
  "Own Resources Operating": ["Own Resources"],
  "Pacific Coast Energy": ["Pacific Coast"],
  "Paradox Resources": ["Paradox"],
  "Parsley Energy": ["Parsley"],
  "Paxton Resources": ["Paxton"],
  "PDC Energy": ["PDC"],
  "Peak Exploration & Production": [
    "PEAK ENERGY CORPORATION",
    "PEAK ENERGY LLC",
    "PEAK ENERGY, LLC",
    "PEAK ENERGY, LLC.",
    "Peak Exploration & Production",
    "PEAK OIL TOOLPEAK OPERATING CO.",
    "PEAK OPERATING OF TEXAS, LLC",
    "PEAK OPERATOR LLC",
    "PEAK TEXAS RESOURCES, LLC",
    "PEAK TRADING CO."
  ],
  "Penn Virginia": ["Penn Virginia"],
  "Pennsylvania General Energy": [
     "Pennsylvania Dril"
    ,"Pennsylvania Gr"
    ,"Pennsylvania In"
    ,"Pennsylvania Rail"
  ],
  "Pennsylvania Land Resources": ["Pennsylvania Land"],
  "PER Manager": ["PER Manager"],
  "Percussion Petroleum": ["Percussion"],
  "Permian Resources Holdings": [
    "PERMIAN RESOURCES", 
    "PERMIAN NATURAL",
    "PERMIAN EXP",
    "Permian Deep Rock Oil Co., Llc (Private)"
  ],
  "Petro Harvester Oil & Gas": ["Petro Harvester"],
  "Petrobal Omega": ["Petrobal"],
  "Petro-Hunt": ["Petro-Hunt","Petro Hunt", "PetroHunt "],
  "Petroshale": ["Petroshale"],
  "Presidio Petroleum": [
     "PRESIDIO ENERGY, INC."
    ,"PRESIDIO EXPLORATION, INC."
    ,"PRESIDIO OIL & GAS, INC."
  ],
  "Pintail Oil & Gas": ["Pintail"],
  "Pioneer Natural Resources": ["Pioneer"],
  "Primexx Operating": ["Primexx"],
  "Pruet Production": ["Pruet"],
  "QEP Resources": ["QEP"],
  "Range Resources": ["RANGE O","RANGE P","RANGE R"],
  "Recoil Resources Operating": ["Recoil Resources Operating"],
  "Repsol": ["Repsol"],
  "Resolute FP": ["Resolute"],
  "Resource Energy Can-Am": ["Resource Energy","Can-Am"],
  "Rimrock Oil & Gas": ["Rimrock"],
  "Rio Grande E&P": ["Rio Grande"],
  "Roan Resources": ["ROANOKE CORPORATION"],
  "Robert R Donnelly": ["Donnelly"],
  "Robertson-Finley Resources": ["ROBERTSON RESOURCES, INC"],
  "Rockall Energy": ["Rockall"],
  "Rockcliff Energy": ["Rockcliff"],
  "Rosehill Resources": ["Rosehill"],
  "Rosetta Resources": ["Rosetta"],
  "Sabine Oil & Gas": ["Sabine"],
  "Sage Natural Resources": ["Sage Natural Resources"],
  "Samson Energy": ["Samson Oil","Samson Exp", "Samson Hyd",],
  "Samson Resources": ["Samson Resources"],
  "Sanchez Oil & Gas": ["Sanchez"],
  "Sandridge Energy": ["Sandridge"],
  "Sanguine Gas Exploration": ["Sanguine"],
  "Savant Alaska": ["Savant"],
  "Scout Energy": ["Scout"],
  "Sempra Energy": ["Sempra"],
  "Seneca Resources": ["Seneca"],
  "Sentinel Peak Resources": ["Sentinel"],
  "Sequitur Energy": ["Sequitur"],
  "SHD Oil & Gas": ["SHD O"],
  "Shell": ["Shell"],
  "Sheridan Production": ["Sheridan"],
  "Silver Creek Oil & Gas": ["Silver Creek"],
  "Silverbow Resources": ["Silverbow"],
  "SK Innovation": ["SK &","SK ENT", "SK In"],
  "Slawson": [
    "Slawson Dr",
    "Slawson Ex",
    "Slawson O"
  ],
  "SM Energy": ["SM Energy Co","SM GAS Prod"],
  "SN EF Maverick": ["SN EF"],
  "Southern Ute Indian Tribe": ["Ute E","Ute oil co."],
  "Southland Royalty": ["Southland"],
  "Southwestern Energy": ["Southwestern Energy"],
  "Southwestern Production": [
    "SOUTHWESTERN EXP",
    "SOUTHWESTERN GAS",
    "SOUTHWESTERN INC",
    "SOUTHWESTERN NATURAL GAS, INC.",
    "SOUTHWESTERN OIL",
    "SOUTHWESTERN REF",
    "SOUTHWESTERN-VICKERS",
    "SOUTHWESTERN Prod"
  ],
  "SRC Energy": ["SRC Energy"],
  "Stanolind Production": ["Stanolind"],
  "Stephens Production": [
    "Stephens Energy",
    "Stephens Oil",
    "Stephens Production",
    "Stephens Energy"
  ],
  "Summit Petroleum": ["Summit"],
  "Summit Petroleum Inc.": ["Summit Petroleum Inc."],
  "Sundance Energy": ["Sundance"],
  "Surge Operating": ["Surge"],
  "Susan Jeanne Searls Collier": ["Susan",'Jeanne','Searls','Collier'],
  "Tanos Exploration": ["Tanos"],
  "Tap Rock Operating": ["Tap Rock"],
  "Tapstone Energy": ["Tapstone"],
  "Tecolote Energy": ["Tecolote"],
  "Tellus Energy Group": ["Tellus"],
  "Templar Energy": ["Templar"],
  "Terra Energy Partners": ["Terra "], //overkill
  "Terracore Operating": ["Terracore"],
  "Texas American Resources": ["Texas American"],
  "Texas Petroleum Investment Co": ["Texas Petroleum"],
  "Texland Petroleum": ["Texland"],
  "The Sinclair Cos": ["Sinclair"],
  "Timber Creek Operating": ["Timber Creek", "Timbercreek"],
  "Titan Rock E&P": ["Titan "],
  "Titus Oil & Gas": ["Titus"],
  "Total": ["Total"],
  "TPG Capital Management": ["TPG "],
  "TRC Cypress Group": ["TRC","Cypress"],
  "Trendwell Energy": ["Trendwell"],
  "Triumph Energy Partners": ["Triumph"],
  "Tug Hill Operating": ["Tug Hill"],
  "Ultra Petroleum": ["Ultra"],
  "Unit Corporation": [
    "Unit c",
    "Unit d",
    "Unit p",
    "Unit r"],
  "UpCurve": ["UpCurve"],
  "Urban Oil & Gas Group": ["Urban Oil"],
  "Ursa Resources Group": ["Ursa"],
  "Utah Gas": ["Utah Gas"],
  "Vanguard Natural Resources": ["Vanguard"],
  "Venado Operating": ["Venado"],
  "Verdad Resources": ["Verdad"],
  "Vine Oil & Gas": ["Vine"],
  "Vitruvian Exploration": ["Vitruvian"],
  "Wells Fargo & Co": ["Wells Fargo"],
  "West Bay Exploration": ["West Bay"],
  "White Oak Energy": ["White Oak"],
  "White Rock Oil & Gas": ["hite Rock"],
  "White Star Petroleum": ["White Star"],
  "Whiting Petroleum": ["Whiting"],
  "Wildhorse Resources": ["Wildhorse"],
  "Wold Energy Partners": ["World Oil"],
  "WPX Energy": ["WPX"],
  "XCL Resources": ["XCL"],
  "Zavanna": ["Zavanna"]
};
/*export const FLARE_MONITOR_CATD_MAPPING:{ [key: string]: string }={
  "Abraxas Petroleum Corp (AXAS)": "Abraxas Petroleum",
  "Advance Energy Partners, Llc (Private)": "Advance Energy Partners",
  "Aethon Energy Operating Llc (Private)": "Aethon Energy",
  "Apr Operating Llc (Private)": "APR Operating",
  //"":"ARD Operating",
  "Armor Petroleum, Inc. (Private)":"Armour Energy",
  //"":"Arsenal Energy Holdings",
  "Ascent Energy, Llc. (Private)":"Ascent Resources",
  "Atlas Barnett Llc (ATLA_P)":"Atlas Energy Group",
  //"":"Australis TMS",
  //"":"Axia Energy II",
  "Ballard Exploration Co (Private)":"Ballard Petroleum Holdings",
  "Battalion Oil Corp (BATL)":"Battalion Oil",
  //"":"BCE-Mach",
  //"":"Bedrock Energy Partners",
  "Birch Operations, Inc. (Private)":"Birch Resources",
  //"":"Bison Oil & Gas Partners II",
  "Bhp Billiton Pet(Txla Op) Co (BHP)":"BHP Minerals",
  "Bkv Barnett, Llc (Private)":"BKV Operating",
  "Blackbeard Operating, Llc (Private)":"Blackbeard Operating",
  "Blackbrush O & G, Llc (Private)":"Blackbrush O & G",
  //"":"Bluecrest Energy",
  //"":"Blue Ridge Mountain Resources",
  //"":"Bluefin Resources",
  //"":"Bluestone Natural Resources",
  //"":"Bonanza Creek Energy",
  "BP plc (BP)":"BP",
  "Breitburn Operating Lp (BRBU_P)":"Breitburn Energy",
  "Brg Petroleum Inc (BRG_P)":"Bridge Energy",
  "Bruin EP Partners LLC (Private)":"Bruin E&P Partners",
  "Burnett Energy Inc (Private)":"Burnett Oil",
  //"":"Cabot Oil & Gas",
  //"":"Caerus Oil & Gas",
  //"":"Caelus Energy",
  //"":"California Resources",
  "Callon Petroleum Co (CPE)":"Callon Petroleum",
  "Carr Resources, Inc. (Private)":"Carrizo Oil & Gas",
  //"":"Cat Canyon Resources",
  //"":"Castleton Commodities International",
  "Centennial Resource Dev (CDEV)":"Centennial Resource",
  //"":"CCRP Operating",
  //"":"Chaparral Energy",
  "Chesapeake Energy Corp (CHK)":"Chesapeake Energy",
  "Chevron Corp (CVX)": "Chevron",
  //"":"Chief Oil & Gas",
  "Chisholm Energy Operating, Llc (Private)":"Chisholm Energy Holdings",
  "Cimarex Energy Co (XEC)":"Cimarex Energy",
  "Citation Oil and Gas Corp (Private)":"Citation Oil & Gas",
  //"":"Citizen Energy",
  //"":"CNX Resources",
  //"":"Colt Alaska",
  //"":"Compass Production Partners",
  "Comstock Resources Inc (CRK)":"Comstock Resources",
  //"":"Concho Resources",
  //"":"Confluence DJ",
  //"":"Contango Resources",
  "ConocoPhillips Co (COP)":"ConocoPhillips",
  //"":"Consol Energy",
  "Continental Resources Inc (CLR)":"Continental Resources",
  //"":"Contura Energy",
  //"":"Cook Inlet Energy",
  //"":"Covey Park Energy",
  //"":"Crestone Peak Resources",
  "Crescent Pass Energy, Llc (Private)":"Crescent Pass Energy",
  //"":"Cross Timbers Energy",
  //"":"Crowheart Energy",
  //"":"Cub Creek Energy",
  "Daylight Petroleum Llc (Private)":"Daylight Petroleum",
  "Denbury Resources Inc (DNR)":"Denbury Resources",
  "Devon Energy Corp (DVN)":"Devon Energy",
  "Diamondback Energy Inc (FANG)":"Diamondback Energy",
  "Discovery Natural Resources Llc (Private)":"Discovery Natural Resources",
  //"":"Diversified Gas & Oil",
  "Djr Operating Llc (DJR_P)":"DJR Energy",
  //"":"Dominion Energy",
  "Dugan Production Corp (DUG_P)":"Dugan Production Corp",
  //"":"Duncan Oil Properties",
  "Earthstone Energy Inc (ESTE)":"Earthstone Energy",
  "Eagle Valley Development Llc (Private)": "Eagle Petroleum",
  "Eagleridge Operating, Llc (Private)": "Eagleridge Operating",
  "Eastland Oil Co (Private)":"Eastland Oil",
  "Elk River Resources, Llc (Private)":"Elk Petroleum",
  //"":"Encana Oil & Gas",
  //"":"Encino Energy",
  "Endeavor Energy Resources LP (Private)":"Endeavor Energy Resources",
  "Enduring Energy LLC (Private)":"Enduring Resources",
  //"":"Energy Corporation of America",
  "Enerplus Corp (ERF)":"Enerplus Resources",
  //"":"EnerVest Operating",
  "Ensign Operating Llc (Private)":"Ensign Natural Resources",
  "EOG Resources Inc (EOG)":"EOG Resources",
  "EP Energy (Private)":"EP Energy",
  //"":"Equal Energy",
  "Equinor ASA (EQNR)":"Equinor",
  "Exxon Mobil Corp (XOM)":"ExxonMobil",
  "Fasken Oil and Ranch Ltd (Private)":"Fasken Oil & Ranch",
  "Foundation Energy Management Llc (Private)":"Foundation Energy",
  //"":"G Arthur Donnelly III",
  //"":"GeoSouthern Energy",
  //"":"Gulfport Energy",
  "Gulftex Energy IV LP (Private)":"GulfTex Energy III",
  //"":"Halcon Resources",
  "Hawkwood Energy LLC (Private)":"Hawkwood Energy Management",
  "Hess Corp (HES)": "Hess",
  //"":"Highpoint Resources",
  //"":"Hinkle Oil & Gas",
  "Hunt Oil Co (Private)":"Hunt Consolidated",
  //"":"Jagged Peak Energy",
  //"":"Jan D O'Neill",
  //"":"Jay-Bee Oil & Gas",
  //"":"JKLM Energy",
  //"":"JMA Energy",
  //"":"Jones Energy",
  //"":"Jordan Development",
  "Kaiser Francis Oil Co (Private)":"Kaiser-Francis Oil",
  //"":"Kash Oil & Gas",
  "Kraken Oil and Gas LLC (Private)":"Kraken Oil & Gas",
  //"":"Lambda Energy Resources",
  "Laredo Petroleum Inc (LPI)":"Laredo Energy",
  "Lewis Energy Group LP (Private)":"Lewis Energy Group",
  "Logos Operating, Llc (Private)":"Logos Resources",
  "Lonestar Resources US Inc (LONE)":"Lonestar Resources",
  "Lonestar R","Lonestar O"],
  "":"Luxe Energy",
  "":"Macpherson Energy",
  "":"Magnolia Oil & Gas",
  "":"Marathon Oil",
  "":"Matador Resources",
  "":"Maverick Natural Resources",
  "":"Memorial Resource Development",
  "":"Merit Energy",
  "":"Mesquite Energy",
  "":"Mewbourne Oil",
  "":"Midstates Petroleum",
  "":"Mission Creek Opco",
  "":"Missouri River Resources",
  "":"Monadnock Resources",
  "":"Montage Resources",
  "":"Murex Petroleum",
  "":"Murphy",
  "":"Muskegon Development Co",
  "":"Nadel & Gussman",
  "":"Naftex Operating",
  "":"National Fuel Gas",
  "":"Natural Gas Partners",
  "":"Newark E&P Operating",
  "":"Newfield Exploration",
  "":"NextEra Energy",
  "":"Nine Point Energy Holdings",
  "":"Noble Energy",
  "":"Northeast Natural Energy",
  "":"Northern Colorado Oil & Gas",
  "":"Northwoods Energy",
  "":"NP Resources",
  "":"Oak Ridge Natural Resources",
  "":"Oasis Petroleum",
  "":"Occidental",
  "":"Orx Resources",
  "":"Own Resources Operating",
  "":"Pacific Coast Energy",
  "":"Paradox Resources",
  "":"Parsley Energy",
  "":"Paxton Resources",
  "":"PDC Energy",
  "":"Peak Exploration & Production",
  "":"Penn Virginia",
  "":"Pennsylvania General Energy",
  "":"Pennsylvania Land Resources",
  "":"PER Manager",
  "":"Percussion Petroleum",
  "":"Permian Resources Holdings",
  "":"Petro Harvester Oil & Gas",
  "":"Petrobal Omega",
  "":"Petro-Hunt",
  "":"Petroshale",
  "":"Presidio Petroleum",
  "":"Pintail Oil & Gas",
  "":"Pioneer Natural Resources",
  "":"Primexx Operating",
  "":"Pruet Production",
  "":"QEP Resources",
  "":"Range Resources",
  "":"Recoil Resources Operating",
  "":"Repsol",
  "":"Resolute FP",
  "":"Resource Energy Can-Am",
  "":"Rimrock Oil & Gas",
  "":"Rio Grande E&P",
  "":"Roan Resources",
  "":"Robert R Donnelly",
  "":"Robertson-Finley Resources",
  "":"Rockall Energy",
  "":"Rockcliff Energy",
  "":"Rosehill Resources",
  "":"Rosetta Resources",
  "":"Sabine Oil & Gas",
  "":"Sage Natural Resources",
  "":"Samson Energy",
  "":"Samson Resources",
  "":"Sanchez Oil & Gas",
  "":"Sandridge Energy",
  "":"Sanguine Gas Exploration",
  "":"Savant Alaska",
  "":"Scout Energy",
  "":"Sempra Energy",
  "":"Seneca Resources",
  "":"Sentinel Peak Resources",
  "":"Sequitur Energy",
  "":"SHD Oil & Gas",
  "":"Shell",
  "":"Sheridan Production",
  "":"Silver Creek Oil & Gas",
  "":"Silverbow Resources",
  "":"SK Innovation",
  "":"Slawson",
  "":"SM Energy",
  "":"SN EF Maverick",
  "":"Southern Ute Indian Tribe",
  "":"Southland Royalty",
  "":"Southwestern Energy",
  "":"Southwestern Production",
  "":"SRC Energy",
  "":"Stanolind Production",
  "":"Stephens Production",
  "":"Summit Petroleum",
  "":"Summit Petroleum Inc.",
  "":"Sundance Energy",
  "":"Surge Operating",
  "":"Susan Jeanne Searls Collier",
  "":"Tanos Exploration",
  "":"Tap Rock Operating",
  "":"Tapstone Energy",
  "":"Tecolote Energy",
  "":"Tellus Energy Group",
  "":"Templar Energy",
  "":"Terra Energy Partners",
  "":"Terracore Operating",
  "":"Texas American Resources",
  "":"Texas Petroleum Investment Co",
  "":"Texland Petroleum",
  "":"The Sinclair Cos",
  "":"Timber Creek Operating",
  "":"Titan Rock E&P",
  "":"Titus Oil & Gas",
  "":"Total",
  "":"TPG Capital Management",
  "":"TRC Cypress Group",
  "":"Trendwell Energy",
  "":"Triumph Energy Partners",
  "":"Tug Hill Operating",
  "":"Ultra Petroleum",
  "":"Unit Corporation",
  "":"UpCurve",
  "":"Urban Oil & Gas Group",
  "":"Ursa Resources Group",
  "":"Utah Gas",
  "":"Vanguard Natural Resources",
  "":"Venado Operating",
  "":"Verdad Resources",
  "":"Vine Oil & Gas",
  "":"Vitruvian Exploration",
  "":"Wells Fargo & Co",
  "":"West Bay Exploration",
  "":"White Oak Energy",
  "":"White Rock Oil & Gas",
  "":"White Star Petroleum",
  "":"Whiting Petroleum",
  "":"Wildhorse Resources",
  "":"Wold Energy Partners",
  "":"WPX Energy",
  "":"XCL Resources",
  "":"Zavanna"
}*/
